"""Problem 45: Triangular, pentagonal, and hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:
    -Triangle: T(n)=n*(n+1)/2 	    1, 3, 6, 10, 15, ...
    -Pentagonal: P(n)=n*(3*n−1)/2   1, 5, 12, 22, 35, ...
    -Hexagonal: H(n)=n*(2*n−1)      1, 6, 15, 28, 45, ...

It can be verified that T(285) = P(165) = H(143) = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

def T(n): return n*(n+1)//2
def P(n): return n*(3*n-1)//2
def H(n): return n*(2*n-1)

n=143 #n is the pointer of H(n) in this case
while 1:
    n+=1
    if ((1+(48*n*n-24*n+1)**.5)/6).is_integer(): break
    
solution=1533776805#=T(l)=P(m)=H(n)
