[package]
name = "projeul_pr243"
version = "0.1.0"
authors = ["stevepapazis <stevepapazis@users.noreply.github.com>"]
edition = "2018"

[[bin]]
name = "projeul_pr243"
path = "projeul_pr243.rs"
test = false
bench = false